---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: jupyter
  labels:
    app: jupyter
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: jupyter
  template:
    metadata:
      labels:
        app: jupyter
        dataset.0.id: "bucket-data"
        dataset.0.useas: "mount"
    spec:
      tolerations:
      - key: nvidia.com/gpu
        operator: Exists
        effect: NoSchedule
      nodeSelector:
        cloud.google.com/gke-accelerator: "nvidia-tesla-t4"
      containers:
      - name: jupyter
        image: "tensorflow/tensorflow:2.13.0-gpu-jupyter"
        resources:
          requests:
            cpu: "6"
            memory: "24Gi"
          limits:
            cpu: "6"
            memory: "24Gi"
            nvidia.com/gpu: 1
        volumeMounts:
        - name: jupyter
          mountPath: /tf/work
        - mountPath: /tf/bucket
          name: "bucket-data"
      volumes:
      - name: jupyter
        persistentVolumeClaim:
          claimName: jupyter-pvc
      - name: "bucket-data"
        persistentVolumeClaim:
          claimName: "bucket-data"
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: jupyter-pvc
  labels:
    app: jupyter
spec:
  storageClassName: premium-rwo
  accessModes:
  - ReadWriteOnce
  resources:
    requests:
      storage: 1Ti
---
apiVersion: com.ie.ibm.hpsys/v1alpha1
kind: Dataset
metadata:
  name: bucket-data
spec:
  local:
    type: "COS"
    accessKeyID: ""
    secretAccessKey: ""
    endpoint: "https://storage.googleapis.com"
    bucket: ""